# https://github.com/tomzo/gocd-yaml-config-plugin
# https://github.com/tomzo/gocd-yaml-config-example

pipelines:
  mypipe:
    group: mygroup

    materials:
      mygit:
        git: https://github.com/abendt/ci-spring-boot-demo.git

    stages:
      - build:
          jobs:
            build:
#              environment_variables:
#                DOCKER_HOST: tcp://10.0.2.15:2375

              artifacts:
                - test:
                  source: target/surefire-reports
                  destination: test-reports

              tasks:
               - exec:
                   command: /bin/sh
                   arguments:
                    - mvnw
                    - verify