pipelines:
  mypipe:
    group: mygroup

    materials:
      mygit:
        git: https://github.com/abendt/ci-spring-boot-demo.git

    stages:
      - build:
          jobs:
            build:
              environment_variables:
                DOCKER_HOST: tcp://10.0.2.15:2375
              tasks:
               - exec:
                   command: /bin/sh
                   arguments:
                    - mvnw
                    - verify