# https://github.com/tomzo/gocd-yaml-config-plugin
# https://github.com/tomzo/gocd-yaml-config-example

pipelines:
  mypipe:
    group: gocd-yaml

    materials:
      github:
        git: https://github.com/abendt/ci-spring-boot-demo.git

    stages:
      - build:
          jobs:
            build:
              artifacts:
                - test:
                    source: target/surefire-reports
                - test:
                    source: target/failsafe-reports

              tasks:
               - exec:
                   command: /bin/sh
                   arguments:
                    - mvnw
                    - verify