resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/abendt/ci-spring-boot-demo.git
      branch: master

jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/concourse/tasks/package.yml
