platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk:8-jdk
    tag: latest

inputs:
  - name: source-code

run:
  path: "source-code/mvnw"
  args: ["-f", "source-code/pom.xml", "verify"]

params:
  MAVEN_BASEDIR: source-code
