platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
  - name: source-code

run:
  path: "source-code/mvnw"
  args: ["-Pci",  "-f", "source-code/pom.xml", "verify"]

params:
  MAVEN_BASEDIR: source-code
  DOCKER_HOST: http://10.0.2.15:4243