---
- hosts: all
  sudo: true
  tasks:
    - name: updates a server
      apt: update_cache=yes

    - name: upgrade a server
      apt: upgrade=dist

    - name: create directory
      file: path=/opt/app state=directory

    - name: copy application
      copy:
           src: ../../../target/concourse-maven-spring-boot-0.0.1-SNAPSHOT.jar
           dest: /opt/app/app.jar